---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app-deployment
  namespace: basic-app
spec:
  replicas: 3 # delete this line if you want to use HPA
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: basic-app-container
        image: basic-app:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: basic-app-service
  namespace: basic-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: basic-app

# that as a bonus if we would like to make use of our custom metrics we can use the following HPA:
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: basic-app-hpa
#   namespace: basic-app
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: basic-app
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50
#   # custom metric
#   - type: Pods
#     pods:
#       metric:
#         name: requests_per_second
#       target:
#         type: AverageValue
#         averageValue: 3000m # 3000m = 3 request per second
#   - type: Pods
#     pods:
#       metric:
#         name: average_request_duration_seconds
#       target:
#         type: AverageValue
#         averageValue: 500 # 500ms
